In [1]:
import os
import numpy as np

#cwd = os.path.dirname(os.path.abspath("C:\Users\Vonag\Downloads\Project\Project\datapoints\in1.txt"))
cwd = r"C:\Users\Vonag\Downloads\Project\Project"
print(cwd)
inputfile = open(r"C:\Users\Vonag\Downloads\Project\Project\datapoints\in1.txt")
delta = 30

def inputStringGenerator() -> list:           #reads from txt file and creates the 2 strings of input for sequence alignment
    count = 0
    inputString1 = ''
    inputString2 = ''
    with open(os.path.join(cwd, 'SampleTestCases', 'input1.txt'), 'r', encoding='UTF-8') as file:
        while line := file.readline().rstrip():
            if(line.isalpha() and not inputString1): 
                inputString1 = line
                count += 1
                continue
            elif(line.isalpha() and not inputString2):
                inputString2 = line
                count += 1
                continue

            line = int(line) + 1
            if(count == 1):
                inputString1 = inputString1[:line] + inputString1 + inputString1[line:]
            else:
                inputString2 = inputString2[:line] + inputString2 + inputString2[line:]

    return [inputString1, inputString2]

def similarityMatrix(char1, char2):
    # Creates a list containing 4 lists, each of 4 items, set the alpha costs
    w, h = 4, 4
    Matrix = [[0 for x in range(w)] for y in range(h)] 
    #A=0,C=1,G=2,T=3
    Matrix = [[0,110,48,94],[110,0,118,48],[48,118,0,110],[94,48,110,0]]
    #bad code but couldnt think of anything else other than a bunch of if else statements at 1230am
    if char1 == 'A':
        i = 0
    elif char1 == 'C':
        i = 1
    elif char1 == 'G':
        i = 2
    elif char1 == 'T':
        i = 3
    if char2 == 'A':
        j = 0
    elif char2 == 'C':
        j = 1
    elif char2 == 'G':
        j = 2
    elif char2 == 'T':
        j = 3

    return Matrix[i][j]

def basicSegmentNeedleman(a, b):
    #initialize dynamic programming array
    w, h = len(a) + 1, len(b) + 1
    #nw_array = [[0 for x in range(w)] for y in range(h)] 
    nw_array = np.zeros((w,h))
    #run the needleman wunsch algorithm to create the opt array where the opt solution is
    for i in range(w):
        for j in range(h):
            if i == 0:
                nw_array[i][j] = j*30
            elif j == 0:
                nw_array[i][j] = i*30
            else:
                #Match ← F(i−1, j−1) + S(Ai, Bj) where S is the similarity between the letters
                match = nw_array[i-1][j-1] + similarityMatrix(a[i-1], b[j-1])
                #Delete ← F(i−1, j) + d
                delete = nw_array[i-1][j] + 30
                #Insert ← F(i, j−1) + d
                insert = nw_array[i][j-1] + 30
                #F(i,j) ← max(Match, Insert, Delete)
                #nw_array[i][j] = max(match,delete,insert)
                nw_array[i][j] = min(match, delete,insert)



    return nw_array
def alphaCost():
# Creates a list containing 4 lists, each of 4 items, set the alpha costs
    w, h = 4, 4
    Matrix = [[0 for x in range(w)] for y in range(h)] 
    Matrix = [[0,110,48,94],[110,0,118,48],[48,118,0,110],[94,48,110,0]]

    return Matrix
    

if __name__ == "__main__":             #main driver
    inputs = inputStringGenerator()
    inputString1 = inputs[0]
    inputString2 = inputs[1]
    Matrix = alphaCost()
    dp_array = basicSegmentNeedleman(inputString1,inputString2)
    print(inputs[0] + "\n" + inputs[1])
    print(Matrix)
    print(dp_array)

C:\Users\Vonag\Downloads\Project\Project
ACACACTGACTACTGACTGGTGACTACTGACTGGACTGACTACTGACTGGTGACTACTGACTGG
TATTATTATACGCTATTATACGCGACGCGGACGCGTATACGCTATTATACGCGACGCGGACGCG
[[0, 110, 48, 94], [110, 0, 118, 48], [48, 118, 0, 110], [94, 48, 110, 0]]
[[   0.   30.   60. ... 1860. 1890. 1920.]
 [  30.   60.   30. ... 1830. 1860. 1890.]
 [  60.   78.   60. ... 1800. 1830. 1860.]
 ...
 [1860. 1830. 1800. ... 1296. 1314. 1344.]
 [1890. 1860. 1830. ... 1266. 1296. 1314.]
 [1920. 1890. 1860. ... 1260. 1290. 1296.]]
